# // the following a set of instructions in the MSP430G2553 mapped to numbers.
# // i'll also be adding registers and stuff


Opcode = {
  'jne' : '20',
  'jnz' : '20',
  'jeq' : '24',
  'jz' : '24',
  'jnc' : '28',
  'jc' : '2c',
  'jn' : '30',
  'jge' : '34',
  'jl' : '38',
  'jmp' : '3c',
  'mov' : '4',
  'mov.w' : '4',
  'mov.b' : '4',
  'inc'   : '5',
  'dec'   : '7',
  'add':'5',
  'add.w':'5',
  'add.b':'5',
  'addc':'6',
  'addc.w':'6',
  'addc.b':'5',
  'subc':'7',
  'subc.w':'7',
  'subc.b':'7',
  'sub':'8',
  'sub.w':'8',
  'sub.b':'7',
  'cmp':'9',
  'cmp.w':'9',
  'cmp.b':'9',
  'dadd':'a',
  'dadd.w' :'a',
  'dadd.b' :'a',
  'bit':'b',
  'bit.w':'b',
  'bit.b':'b',
  'bic':'c',
  'bic.w':'c',
  'bic.b':'c',
  'bis':'d',
  'bis.w':'d',
  'bis.b':'d',
  'xor':'e',
  'xor.w':'e',
  'xor.b':'e',
  'and':'f',
  'and.w':'f',
  'and.b':'f'
}
OperandType = {
    'jne' : 'JMP',
    'jnz' : 'JMP',
    'jeq' : 'JMP',
    'jz' : 'JMP',
    'jnc' : 'JMP',
    'jc' : 'JMP',
    'jn' : 'JMP',
    'jge' : 'JMP',
    'jl' : 'JMP',
    'jmp' : 'JMP',
    'mov' : 'Double',
    'mov.w' : 'Double',
    'mov.b' : 'Double',
    'inc'   : 'Double',
    'dec'   : 'Double',
    'add':'Double',
    'add.w':'Double',
    'add.b':'Double',
    'addc':'Double',
    'addc.w':'Double',
    'addc.b':'Double',
    'subc':'Double',
    'subc.w':'Double',
    'subc.b':'Double',
    'sub':'Double',
    'sub.w':'Double',
    'sub.b':'Double',
    'cmp':'Double',
    'cmp.w':'Double',
    'cmp.b':'Double',
    'dadd':'Double',
    'dadd.w' :'Double',
    'dadd.b' :'Double',
    'bit':'Double',
    'bit.w':'Double',
    'bit.b':'Double',
    'bic':'Double',
    'bic.w':'Double',
    'bic.b':'Double',
    'bis':'Double',
    'bis.w':'Double',
    'bis.b':'Double',
    'xor':'Double',
    'xor.w':'Double',
    'xor.b':'Double',
    'and':'Double',
    'and.w':'Double',
    'and.b':'Double'
}

Registers = {
    'R0' : '0',
    'R1' : '1',
    'R2' : '2',
    'R3' : '3',
    'R4' : '4',
    'R5' : '5',
    'R6' : '6',
    'R7' : '7',
    'R8' : '8',
    'R9' : '9',
    'R10' : 'a',
    'R11' : 'b',
    'R12' : 'c',
    'R13' : 'd',
    'R14' : 'e',
    'R15' : 'f'
}
allowed =["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P",
        "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f",
        "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v",
        "w", "x", "y", "z", "0", "1", "2", "3" , "4", "5", "6", "7", "8", "9" ,"_", " "]
